#!/bin/bash

# MoneyWise Backend - Supabase Credentials Helper
# This script helps you get your Supabase database credentials

set -e

echo "🔑 MoneyWise Backend - Supabase Credentials Setup"
echo "=================================================="
echo

# Check if .env file exists
if [ -f ".env" ]; then
    echo "⚠️  .env file already exists"
    read -p "Do you want to overwrite it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "❌ Setup cancelled"
        exit 1
    fi
fi

echo "📋 To get your Supabase credentials, follow these steps:"
echo
echo "1. Go to https://supabase.com and sign in"
echo "2. Select your project (or create a new one)"
echo "3. Go to Settings → Database"
echo "4. Copy the connection string and other details"
echo

# Get project reference
read -p "Enter your Supabase project reference (e.g., abcdefghijklmnop): " PROJECT_REF

if [ -z "$PROJECT_REF" ]; then
    echo "❌ Project reference is required"
    exit 1
fi

# Get database password
read -s -p "Enter your database password: " DB_PASSWORD
echo

if [ -z "$DB_PASSWORD" ]; then
    echo "❌ Database password is required"
    exit 1
fi

# Get region
read -p "Enter your region (e.g., us-east-1, eu-west-1): " REGION

if [ -z "$REGION" ]; then
    echo "❌ Region is required"
    exit 1
fi

# Get anon key
read -p "Enter your anon key (Settings → API): " ANON_KEY

if [ -z "$ANON_KEY" ]; then
    echo "❌ Anon key is required"
    exit 1
fi

# Create .env file
echo "📝 Creating .env file..."

cat > .env << EOF
# MoneyWise Backend Environment Configuration
# Generated by get-supabase-credentials.sh

# Database Configuration (Supabase)
DATABASE_URL=postgresql://postgres.${PROJECT_REF}:${DB_PASSWORD}@aws-0-${REGION}.pooler.supabase.com:6543/postgres
SUPABASE_URL=https://${PROJECT_REF}.supabase.co
SUPABASE_ANON_KEY=${ANON_KEY}

# Application Settings
RUST_LOG=info
HOST=127.0.0.1
PORT=3000

# Optional Redis Configuration
# REDIS_URL=redis://localhost:6379
EOF

echo "✅ .env file created successfully!"
echo
echo "🔍 Your configuration:"
echo "   Project: ${PROJECT_REF}"
echo "   Region: ${REGION}"
echo "   Database URL: postgresql://postgres.${PROJECT_REF}:***@aws-0-${REGION}.pooler.supabase.com:6543/postgres"
echo "   Supabase URL: https://${PROJECT_REF}.supabase.co"
echo
echo "🚀 Next steps:"
echo "   1. Verify your credentials are correct"
echo "   2. Run: make setup"
echo "   3. Or run: ./setup.sh"
echo
echo "📚 For more help, see README.md"
