#!/bin/bash

# MoneyWise Backend - Supabase Credentials Helper
# This script helps you get your Supabase database credentials

# Load core utilities
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MODULE_LOADER="$SCRIPT_DIR/../core/module-loader.sh"

# Load module loader first
if [ ! -f "$MODULE_LOADER" ]; then
    echo "❌ Error: Module loader not found at $MODULE_LOADER"
    exit 1
fi

source "$MODULE_LOADER"

# Load additional utilities
ENV_UTILS="$SCRIPT_DIR/../core/env-utils.sh"
CHECK_UTILS="$SCRIPT_DIR/../core/check-utils.sh"

source "$ENV_UTILS"
source "$CHECK_UTILS"

echo "🔑 MoneyWise Backend - Supabase Credentials Setup"
echo "=================================================="
echo

# Check if .env file exists
if check_file_exists ".env" "Environment file" false; then
    print_warning ".env file already exists"
    read -p "Do you want to overwrite it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        print_error "Setup cancelled"
        exit 1
    fi
fi

print_status "To get your Supabase credentials, follow these steps:"
echo
echo "1. Go to https://supabase.com and sign in"
echo "2. Select your project (or create a new one)"
echo "3. Go to Settings → Database"
echo "4. Copy the connection string and other details"
echo

# Get project reference
read -p "Enter your Supabase project reference (e.g., abcdefghijklmnop): " PROJECT_REF

if [ -z "$PROJECT_REF" ]; then
    print_error "Project reference is required"
    exit 1
fi

# Get database password
read -s -p "Enter your database password: " DB_PASSWORD
echo

if [ -z "$DB_PASSWORD" ]; then
    print_error "Database password is required"
    exit 1
fi

# Get region
read -p "Enter your region (e.g., us-east-1, eu-west-1): " REGION

if [ -z "$REGION" ]; then
    print_error "Region is required"
    exit 1
fi

# Get anon key
read -p "Enter your anon key (Settings → API): " ANON_KEY

if [ -z "$ANON_KEY" ]; then
    print_error "Anon key is required"
    exit 1
fi

# Create .env file
print_status "Creating environment file..."

# Create environment content
ENV_CONTENT="# MoneyWise Backend Environment Configuration
# Generated by get-supabase-credentials.sh

# Database Configuration (Supabase)
DATABASE_URL=postgresql://postgres.${PROJECT_REF}:${DB_PASSWORD}@aws-0-${REGION}.pooler.supabase.com:6543/postgres
SUPABASE_URL=https://${PROJECT_REF}.supabase.co
SUPABASE_ANON_KEY=${ANON_KEY}

# Application Settings
RUST_LOG=info
HOST=127.0.0.1
PORT=3000

# Optional Redis Configuration
# REDIS_URL=redis://localhost:6379"

# Write environment file using env-utils
if echo "$ENV_CONTENT" > .env; then
    print_success ".env file created successfully!"
    echo
    print_status "Your configuration:"
    echo "   Project: ${PROJECT_REF}"
    echo "   Region: ${REGION}"
    echo "   Database URL: postgresql://postgres.${PROJECT_REF}:***@aws-0-${REGION}.pooler.supabase.com:6543/postgres"
    echo "   Supabase URL: https://${PROJECT_REF}.supabase.co"
    echo
    print_status "Next steps:"
    echo "   1. Verify your credentials are correct"
    echo "   2. Run: make setup"
    echo "   3. Or run: ./setup.sh"
    echo
    print_info "For more help, see README.md"
else
    print_error "Failed to create .env file"
    exit 1
fi